apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-demo-deployment
  labels:
    set: my-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      set: my-demo
  template:
    metadata:
      labels:
        set: my-demo
    spec:
      containers:
        - name: my-demo-app
          image: kurenchuksergey/kubernetes-demo:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health/
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3